### ISSUE TITLE
ZFE_TRAVEL_###### instead of ZC_FE_TRAVEL_######

### ISSUE THREAD

**Issue by bartik** [SAP-samples/fiori-elements-opensap#1]
unit6.md

Step 7. Description instead of Codes for the status field

3. With these settings the description is displayed in the column Status but additionally, the code is shown within parentheses. You can use the @UI.textArrangement annotation with value #TEXT_ONLY to omit the key. Open the metadata extension file ZC_FE_TRAVEL_###### and add the text arrangement annotation to the field OverallStatus (line 3).

Should be ZFE_TRAVEL_###### instead of ZC_FE_TRAVEL_###### ?

**Comment by stefan0816** [comment]
Hi Bartik,

I checked this, in https://github.com/SAP-samples/fiori-elements-opensap/blob/main/week1/unit6.md#step-2-create-a-metadata-extension-file-for-the-travel-entity the suggestion is to name the metadata extension `ZC_FE_TRAVEL_######`:

![](https://github.com/SAP-samples/fiori-elements-opensap/raw/main/week1/images/unit6/MetadataExtension_2.png)

So 3. is correct if you followed the naming suggestion. Maybe you gave it a different name?

Best regards,
Stefan

**Comment by bartik** [comment]
Yes you are correct. I named it ZFE_TRAVEL_XXX.
