### ISSUE TITLE
Still unable to create a package

### ISSUE THREAD

**Issue by realfeel75** [SAP-samples/fiori-elements-opensap#10]
Hello,
I have the same problem as mentioned in the closed thread "Unable to create a package". The package can't be created. Message:
DEVC ZFE_TRAVELING_000000: Object R3TR DEVC ZFE_TRAVELING_000000 is already locked on transport request TRLK900814.

URL:
https://45f514af-f57b-4579-990b-8b70ea328491.abap.us10.hana.ondemand.com

Thanks

**Comment by DianaOommachan** [comment]
Getting same error when trying to create the package from the generator class.

System URL is: https://45f514af-f57b-4579-990b-8b70ea328491.abap.us10.hana.ondemand.com

**Comment by stefan0816** [comment]
We are already looking into it. Will let you know once it's back working.

**Comment by realfeel75** [comment]
I checked today and I was able to get the objects generated. I suppose the issue is resolved. Thanks

**Comment by DianaOommachan** [comment]
Package got created for me as well. Thank you

**Comment by stefan0816** [comment]
The colleague who looked into it just came back to me and said he had fixed it earlier today :). Some participants deleted their package but didn't release the transport request. That's why the automatic project creation struggled. We will optimize that in the future.
