### ISSUE TITLE
Not able to see Publish in Service binding for my pacakge.

### ISSUE THREAD

**Issue by Kaleshavalli** [SAP-samples/fiori-elements-opensap#4]
Hi ,
Greetings !
I have installed ADT in my Eclipse and connected to Trail system. As part of the Unit 1 exercise i double click on the Service Binding ZUI_FE_BOOKING_000644_O2 but i could not find the Publish button. Can you please help me what i am missing and kindly assist on this. Here is the screen shot of the issue.
Thanking you in advance.
Thanks & Regards,
Kalesha.
![Publish button issue in Service Binding](https://user-images.githubusercontent.com/87090728/124810258-ba55f180-df7e-11eb-98f5-8a68f57ddc08.PNG)

**Comment by stefan0816** [comment]
Hey Kalesha,

I would guess your ADT version is too old. In my Eclipse also the icons look differently:
![image](https://user-images.githubusercontent.com/35706403/124877117-10508680-dfcb-11eb-8ff6-56e3f8d55939.png)

Can you try "Help" -> "Check for Updates". If it doesn't offer a newer version, can you check if your Eclipse installation is very old?

Best regards,
Stefan

**Comment by Kaleshavalli** [comment]
HI Stefan,
Thank you so much for quick response. I have checked and done the Updates. And i see that i have installed Latest ADT version.
Can you please check the attached screen shot. 
Still i see different icon for Service Bindings in my package comparing to your image. Can you please suggest or any URL from where i can download the latest version to fix the issue. So that i will uninstall and follow the steps to install required versions to fix the issue and continue my practice. Thanking you in advance.
Thanks & Regards,
Kalesha.
![Publish button issue in Service Binding 1](https://user-images.githubusercontent.com/87090728/124893916-cbdbdf80-dff8-11eb-920d-9e38890ed48a.PNG)

**Comment by stefan0816** [comment]
Hi Kalesha,

can you open "Help" -> "About ABAP Development Tools" (could possibly also be called "About Eclipse"). Then click on "Installation Details" and share a screenshot on which the installed modules and their versions can be seen. 

Best regards,
Stefan

**Comment by Kaleshavalli** [comment]
HI Stefan,
Please find the below screen shots with Installation details.
Thanking you in advance.
Thanks & Regards,
Kalesha.
![image1](https://user-images.githubusercontent.com/87090728/125122674-63cdec00-e113-11eb-9ef2-d15f91503da1.PNG)
![image2](https://user-images.githubusercontent.com/87090728/125122680-66304600-e113-11eb-9db7-9dcc25640410.PNG)

**Comment by stefan0816** [comment]
Hi Kalesha,

I asked an ADT expert to look into it. Will come back to you.

Best regards,
Stefan

**Comment by Kaleshavalli** [comment]
Hi Stefan,
Ok thank you. Please let me know if you heard anything from him, so that i will followup accordingly.
Looking forward to hear.
Have a nice day !.

Thanks & Regards,
Kalesha.

**Comment by Kaleshavalli** [comment]
Hi Stefan,
Greetings for the day!
If you heard any update from ADT expert could you please let me know about this issue.
Thanking you in advance.

Thanks & Regards,
Kalesha.

**Comment by stefan0816** [comment]
Hi Kalesha,

the expert was also wondering what could be the reason :). Are you connected to a VPN while you are trying this? If yes, can you please disconnect from VPN? Or do you have installed a very strict firewall? 

Best regards,
Stefan

**Comment by koradaramjee789** [comment]
Hi Kalesha,

I got similar error when executing generator class and got solved after updating ABAP instance. 
Not sure if helps but you can give a try.

PFB

![image](https://user-images.githubusercontent.com/68756266/126588245-4fdbd4ef-eaf8-46a9-bc9b-c7e13af32acc.png)

Best wishes,
Ramjee

**Comment by Kaleshavalli** [comment]
Hi Stefan,
I am not using any VPN in my personal laptop.
@Ramjee : Thank you for the input i have updated the ABAP Instance and same is repeated.

But as a Final try i have done as below and it finally resolved the issue.
I have uninstalled my Eclipse and Followed the steps from starting by re installing Eclipse and ABAP perspective in my Eclipse environment and it worked.

I really appreciate you both Stefan and Ramjee for spending your valuable time for guiding me. Thanking you Both.
Have a wonderful day !

Thanks & Regards,
Kalesha.
![Issue Fixed](https://user-images.githubusercontent.com/87090728/126616989-3baf0a2c-30b2-4a57-ac78-7c83473e600a.PNG)
