### ISSUE TITLE
[Week 3 / Unit 3 / Step 3 ] Getting erroneous metadata while Adding new OData V4 service from Service Manager

### ISSUE THREAD

**Issue by koradaramjee789** [SAP-samples/fiori-elements-opensap#5]
Dear Experts,

I am getting error Getting erroneous metadata  while Adding new OData V4 service from Service Manager

[Week 3 / Unit 3 / Step 3 ] (https://github.com/SAP-samples/fiori-elements-opensap/blob/main/week3/unit3.md#step-3-add-odata-v4-service-from-service-manager).

1. Service is added successfully. 

![image](https://user-images.githubusercontent.com/68756266/126589173-2446b664-0bc8-4d5e-9263-af53437460e8.png)
2. But the metadata is erroneous . 
![image](https://user-images.githubusercontent.com/68756266/126589224-348753fb-a08a-48ca-8cdf-99e20089699c.png)

Because of this, I am not able to proceed further . 

Best wishes,
Ramjee

**Comment by rohit-chaudhary1** [comment]
Hello Ramjee,

Although you are getting this error it should not stop you from proceeding further. Are you not able to proceed after this step? Can you elaborate a little more on what step you are facing issue and the issue? Screenshots would help.

Regards,
Rohit

**Comment by koradaramjee789** [comment]
Hi Rohit,

It worked now. 
I tried couple of times earlier but did not work. After I press "Insert Snippet" , it was navigating to Metadata xml instead of annotation0.xml.

Best wishes,
Ramjee
