### ISSUE TITLE
Can not find Data Source and Service Platform to connect to SAP System

### ISSUE THREAD

**Issue by novemberrain11** [SAP-samples/fiori-elements-opensap#6]
Hello team, Could you please help to check. I have tried with SAP Business Application Studio and Visual Studio Code, but I do not have the option to choose: "Connect to SAP System".

![image](https://user-images.githubusercontent.com/87578356/126904971-e4b9a6f3-21f6-47a0-90c7-9b84c41775d2.png)

Thanks.

**Comment by stefan0816** [comment]
Hey,

this was renamed recently. Please use "Connect to a System".

Best regards,
Stefan
