### ISSUE TITLE
Unable to create package

### ISSUE THREAD

**Issue by RajeshKuppa** [SAP-samples/fiori-elements-opensap#8]
Hi, 
I am facing issue at step Week 1 Unit 5: Creating an OData service.
While executing the class /dmo/cl_fe_travel_generator am getting message in console .
PUT operation failed.
Class name:
CX_XCO_GEN_PUT_EXCEPTION
Source position:
Line 8 of EXECUTE in CL_XCO_GEN_O_PUT_ABSTRACT
Additional messages:
DEVC ZFE_TRAVEL_000**: Object R3TR DEVC ZFE_TRAVEL_000** is already locked on transport request TRL***.

After that above package is not visible while adding to favorite.
Can you please advice how to proceed further on this.

Regards,
Rajesh K

**Comment by stefan0816** [comment]
Hi Rajesh,

we are aware of the issue and a transport with a fix is already on its way. Should be working by EOB today. Will keep you posted.

Best regards,
Stefan

**Comment by RajeshKuppa** [comment]
Thank you stefan, issue solved.

**Comment by RajeshKuppa** [comment]
Package creation issue is solved, but it does not have any objects.
Empty package got created, can you please check again

**Comment by stefan0816** [comment]
Can you try again now? If the problem persists, can you right-click at the ABAP Cloud Project -> Properties -> ABAP Development and then tell me the "System URL"?

**Comment by pardojavi** [comment]
Hello, 
I have the same error and can't create the package.
The system URL is :
https://fafe2a05-536e-4ed6-b44f-4ad66ae6bfb7.abap.eu10.hana.ondemand.com

Everything is correct?

Thanks.

**Comment by phdaucourt** [comment]
Hi,

Similar problem for me too. A new package and a new transport request are created but the package is totally empty.

Here is the message I get when I run the generator:

SAP Fiori elements exercise generator 
 ------------------------------------- 
 The following package got created for you and includes everything you need: ZFE_TRAVEL_000117 
 In the "Project Explorer" right click on "Favorite Packages" and click on "Add Package...". Enter "ZFE_TRAVEL_000117" and click OK. 
PUT operation failed.
Class name:
CX_XCO_GEN_PUT_EXCEPTION
Source position:
Line 8 of EXECUTE in CL_XCO_GEN_O_PUT_ABSTRACT
Additional messages:
DDLS ZI_FE_STAT_000117: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_CARR_000117: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_CONN_000117: Creation of CDS views is not allowed in the current environment.
DDLS ZI_FE_FLIG_000117: Creation of CDS views is not allowed in the current environment.

Thanks for your help.

**Comment by stefan0816** [comment]
For the trial system with the URL https://fafe2a05-536e-4ed6-b44f-4ad66ae6bfb7.abap.eu10.hana.ondemand.com it's now working. A colleague with a user in that system just tried it an hour ago and the package and its contents were successfully generated. Can you guys try again? If the problem persists, can you right-click at the ABAP Cloud Project -> Properties -> ABAP Development and then tell me the "System URL"?

**Comment by phdaucourt** [comment]
I've just retried. Same problem as yesterday. I'm using the trial system with the URL https://f53f7607-c777-4233-b357-b0090de15eda.abap.us10.hana.ondemand.com.

**Comment by phdaucourt** [comment]
I've just created a Frankfurt subaccount which has the URL https://5422bbff-4781-4b19-8ca9-5f7ac9d4a30b.abap.eu10.hana.ondemand.com and the generator is working fine in this system.

**Comment by pardojavi** [comment]
The system is working fine for me too.
Thanks.

**Comment by stefan0816** [comment]
In case someone is still facing the issue feel free to reopen the issue or create a new one. Have fun with the exercise! 😊
